//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sifaeczadeposu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilaclar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ilaclar()
        {
            this.satinalma = new HashSet<satinalma>();
        }
    
        public int ID { get; set; }
        public string ilacadi { get; set; }
        public string aciklama { get; set; }
        public int fiyat { get; set; }
        public byte[] resim { get; set; }
        public Nullable<int> indirimorani { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satinalma> satinalma { get; set; }
    }
}
