//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sifaeczadeposu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class satinalma
    {
        public int ID { get; set; }
        public int FKilacID { get; set; }
        public int FKuyeID { get; set; }
        public byte[] resim { get; set; }
        public string k_ad { get; set; }
        public string sifre { get; set; }
        public int fiyat { get; set; }
        public Nullable<int> indirimorani { get; set; }
    
        public virtual ilaclar ilaclar { get; set; }
        public virtual uye uye { get; set; }
    }
}
