//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sifaeczadeposu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sifaeczadposuEntities : DbContext
    {
        public sifaeczadposuEntities()
            : base("name=sifaeczadposuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fuar> fuar { get; set; }
        public virtual DbSet<fuarkayit> fuarkayit { get; set; }
        public virtual DbSet<ilaclar> ilaclar { get; set; }
        public virtual DbSet<satinalma> satinalma { get; set; }
        public virtual DbSet<uye> uye { get; set; }
        public virtual DbSet<duyurular> duyurular { get; set; }
        public virtual DbSet<onerisikayet> onerisikayet { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
