//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sifaeczadeposu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int ID { get; set; }
        public byte[] SliderFoto { get; set; }
        public string SliderText { get; set; }
        public System.DateTime BaslangicTarih { get; set; }
        public System.DateTime BitisTarih { get; set; }
    }
}
